version: 2

formats: all

python:
   version: 3.6
#   install:
#      - method: pip
#        path: .
#        extra_requirements:
#            - sphinx
#            - sphinx_rtd_theme

conda:
  environment: base_environment.yml

build:
  image: latest

sphinx:
  fail_on_warning: true
